package com.server.controller;

public enum ControllerDataRaw {
    NULL,

    A_BUTTON_PRESS,
    B_BUTTON_PRESS,
    Y_BUTTON_PRESS,
    X_BUTTON_PRESS,
    RB_BUTTON_PRESS,
    LB_BUTTON_PRESS,
    START_BUTTON_PRESS,
    BACK_BUTTON_PRESS,
    UP_BUTTON_PRESS,
    DOWN_BUTTON_PRESS,
    LEFT_BUTTON_PRESS,
    RIGHT_BUTTON_PRESS,
    UPRIGHT_BUTTON_PRESS,
    UPLEFT_BUTTON_PRESS,
    DOWNRIGHT_BUTTON_PRESS,
    DOWNLEFT_BUTTON_PRESS,
    LEFTSTICK_BUTTON_PRESS,
    RIGHTSTICK_BUTTON_PRESS,

    A_BUTTON_PRESS_RELEASE,
    B_BUTTON_PRESS_RELEASE,
    Y_BUTTON_PRESS_RELEASE,
    X_BUTTON_PRESS_RELEASE,
    RB_BUTTON_PRESS_RELEASE,
    LB_BUTTON_PRESS_RELEASE,
    START_BUTTON_PRESS_RELEASE,
    BACK_BUTTON_PRESS_RELEASE,
    UP_BUTTON_PRESS_RELEASE,
    DOWN_BUTTON_PRESS_RELEASE,
    LEFT_BUTTON_PRESS_RELEASE,
    RIGHT_BUTTON_PRESS_RELEASE,
    UPRIGHT_BUTTON_PRESS_RELEASE,
    UPLEFT_BUTTON_PRESS_RELEASE,
    DOWNRIGHT_BUTTON_PRESS_RELEASE,
    DOWNLEFT_BUTTON_PRESS_RELEASE,
    LEFTSTICK_BUTTON_PRESS_RELEASE,
    RIGHTSTICK_BUTTON_PRESS_RELEASE,


    LEFTSTICK_MOVE_LEFT,
    LEFTSTICK_MOVE_RIGHT,
    LEFTSTICK_MOVE_UP,
    LEFTSTICK_MOVE_DOWN,

    LEFTSTICK_MOVE_LEFT_RELEASE,
    LEFTSTICK_MOVE_RIGHT_RELEASE,
    LEFTSTICK_MOVE_UP_RELEASE,
    LEFTSTICK_MOVE_DOWN_RELEASE,


    RIGHTSTICK_MOVE_LEFT,
    RIGHTSTICK_MOVE_RIGHT,
    RIGHTSTICK_MOVE_UP,
    RIGHTSTICK_MOVE_DOWN,

    RIGHTSTICK_MOVE_LEFT_RELEASE,
    RIGHTSTICK_MOVE_RIGHT_RELEASE,
    RIGHTSTICK_MOVE_UP_RELEASE,
    RIGHTSTICK_MOVE_DOWN_RELEASE
}
